# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.40.0-focal
    steps:
      - checkout
      - run: npm i -D @playwright/test
      # - run: npx playwright install
      - run: npx playwright install --with-deps chrome
      - run:
          name: Run test
          command: PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml npx playwright test --reporter=junit --project=chromium
      - store_test_results:
          path: results.xml
# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test